### ISSUE TITLE
How to throttle Nettosphere used with Satellite

### ISSUE THREAD

**Issue by amit2103** [Atmosphere/nettosphere#115]
Hi 

I have to throttle websocket requests to nettosphere ? Thing is when too much message is being sent to nettosphere, it goes to Netty handlers where if the channel is not writable it buffers in queue. However once too much messages are stored in the queue, it throws an out memory exception. 

What should be our approach to throttle the messages without effecting client code? 
Is there any mechanism available in Nettosphere which can be used to throttle the messages.

**Comment by thabach** [comment]
@amit2103 please use the mailing list for questions.
