### ISSUE TITLE
 buildBootstrap wrongly use the NioServerSocketChannel.class for epoll in linux 

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/nettosphere#117]
In linux, when enable the Epoll, the channel class must be EpollServerSocketChannel.class instead of  NioServerSocketChannel.class   

    private ServerBootstrap buildBootstrap(Config config) {
        final ServerBootstrap bootstrap = new ServerBootstrap();
        parentGroup = config.epoll() ? new EpollEventLoopGroup() : new NioEventLoopGroup();
        childGroup = config.epoll() ? new EpollEventLoopGroup() : new NioEventLoopGroup();
		bootstrap
        	.channel(NioServerSocketChannel.class)
        	.group(parentGroup, childGroup);
        
        bootstrap.childHandler(channelInitializer);
        return bootstrap;
    }

**Comment by dreamershl** [comment]
Because of this issue, the following statement is fail. But there is no way to know the server start is fail with the error "java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop"

    nettosphere.start();

**Comment by jfarcand** [comment]
@dreamershl Do you need a dot release?

**Comment by dreamershl** [comment]
Thanks. yes, if can. want to fully utilize the optimization of Epoll. 

And another issue is recently I keep receiving the memory leak alert from netty #120. After I finish my current project milestone, will try to look into it. I suspect it may also part of reason of issues #104 ( I also encounter this, but not often)

**Comment by jfarcand** [comment]
It's with 3.0 right?

**Comment by dreamershl** [comment]
yes, it is org.atmosphere:nettosphere:3.0.0.RC4
