### ISSUE TITLE
netty report memory leak for the websocket

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/nettosphere#120]
recently I get the memory leak report from the netty. Seems the org.atmosphere.nettosphere.BridgeRuntime.handleWebSocketFrame get some kinds of memory leak issue

![image](https://cloud.githubusercontent.com/assets/1271739/18225224/754b180c-7220-11e6-9a50-63afb17e007c.png)

**Comment by dreamershl** [comment]
In the BridgeRuntime::handleWebSocketFrame, it should call the WebSocketFrame release function to release the buffer. The WebSocketFrame is derived from "DefaultByteBufHolder". The following is the study on this issue.

      WebSocketFrame frame = (WebSocketFrame) messageEvent; 


1. Similar issue is reported in netty https://github.com/netty/netty/issues/2158 
2. From the  netty website http://netty.io/wiki/reference-counted-objects.html

When an event loop reads data into a ByteBuf and triggers a channelRead() event with it, **it is the responsibility of the ChannelHandler in the corresponding pipeline to release the buffer**. Therefore, the handler that consumes the received data should call release() on the data in its channelRead() handler method:

    public void channelRead(ChannelHandlerContext ctx, Object msg) {
    ByteBuf buf = (ByteBuf) msg;
    try {
        ...
    } finally {
        buf.release();
    }
   }
As explained in the 'Who destroys?' section of this document, **if your handler passes the buffer (or any reference-counted object) to the next handler, you don't need to release it**:

    public void channelRead(ChannelHandlerContext ctx, Object msg) {
    ByteBuf buf = (ByteBuf) msg;
    ...
    ctx.fireChannelRead(buf);
    }

**Comment by dreamershl** [comment]
I believe the finding is confirmed by checking the class hierarchy. 

    BridgeRuntime -> HttpStaticFileServerHandler -> SimpleChannelInboundHandler<FullHttpRequest> 

in the SimpleChannelInboundHandler::channelRead, the received msg is released after the process. So to avoid this issue, one solution is to override the "channelRead0" instead of "channelRead" 

     @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        boolean release = true;
        try {
            if (acceptInboundMessage(msg)) {
                @SuppressWarnings("unchecked")
                I imsg = (I) msg;
                channelRead0(ctx, imsg);
            } else {
                release = false;
                ctx.fireChannelRead(msg);
            }
        } finally {
            if (autoRelease && release) {
                ReferenceCountUtil.release(msg);
            }
        }
    }

**Comment by jfarcand** [comment]
@dreamershl Great analysis! Can you do a pull request?

**Comment by dreamershl** [comment]
I have created the pull. pls check. thx

**Comment by jfarcand** [comment]
Thanks. I will cut the new release. Let me know how it goes.

**Comment by dreamershl** [comment]
find another issue. when process the CloseWebSocketFrame, the message is directly passed into the ctx.channel().write(). And it will release the buffer. So need add the refCnt() check in outside function. 
![image](https://cloud.githubusercontent.com/assets/1271739/18665901/ed5ffdb0-7f5b-11e6-9a41-f87a58b5b7a0.png)

**Comment by jfarcand** [comment]
@dreamershl Are you satisfy with 3.0.0 right now? I could release it as final next week.

**Comment by dreamershl** [comment]
Yes, very stable. until now, the random drop issue is also gone ;) Thanks for your great job!!!

Just FYI, 
    Now sometime, my system will report this error. I will monitor it closely. Any findings, will inform u

    GMT 18:01:42,225 E  o.a.n.BridgeRuntime [epollEventLoopGroup-6-1]({})
           Invalid state java.lang.Error and Channel [id: 0x01eb41f8, L:/172.31.9.90:8080 ! R:/138.75.161.167:52420]

**Comment by jfarcand** [comment]
@dreamershl I do see that exception as well, it just means  the socket wasn't closed properly.
