### ISSUE TITLE
Please: Release/Snapshot - 2.4.11-SNAPSHOT

### ISSUE THREAD

**Issue by ricardojlrufino** [Atmosphere/nettosphere#121]
Please, you could launch a snapshot for version: 2.4.11-SNAPSHOT
Branch: https://github.com/Atmosphere/nettosphere/tree/nettosphere-2.4.x

Repo:
https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/nettosphere/

Thanks

**Comment by jfarcand** [comment]
Done!
