### ISSUE TITLE
Cannot stop Nettosphere

### ISSUE THREAD

**Issue by supertick** [Atmosphere/nettosphere#141]
Using nettosphere 3.0.11

nettosphere.stop()  - still leaves 16 nioEventLoopGroup threads.

Perhaps I'm not setting up builder config correctly ?

**Comment by jfarcand** [comment]
@supertick Can you share a test case?

**Comment by supertick** [comment]
Thank you for your project.
A test case is rather trivial, count the threads before you start Nettosphere, start Nettosphere, then stop it ... there are quite a few worker and parent threads I believe which are not shutdown.

The following commit I believe fixes the problem,
https://github.com/MyRobotLab/nettosphere/commit/a77c5eae81187fd100f455094abb453993742da4

Thanks,
Greg

**Comment by supertick** [comment]
something like this ...
get the set of current operating threads .. start nettosphere, stop .. it should be the same ...

`java
    // take snapshot of threads
    Set<Thread> threadSetStart = Thread.getAllStackTraces().keySet();
    nettosphere.start();
    Thread.sleep(2000);
    nettosphere.stop();
     
    Set<Thread> threadSetEnd = Thread.getAllStackTraces().keySet();
    for (Thread thread : threadSetEnd) {
      if (!threadSetStart.contains(thread)) {
             log.error("extra threads found");
       }
     }
      
`

**Comment by jfarcand** [comment]
Released 3.0.12. Thanks

**Comment by supertick** [comment]
Thank for your quick responses.
I think one of your unit tests fails now.
I was curious, what would be the ETA in maven central ?
