### ISSUE TITLE
add ability to configure netty for ssl

### ISSUE THREAD

**Issue by jahlborn** [Atmosphere/nettosphere#17]
it is not currently possible to configure netty directly outside of the simple host,port configuration.  it would be nice to expose more advanced configuration of netty, primarily ssl, but also possibly things like thread pools, socket params, etc.

**Comment by rahulva** [comment]
Hi 
I'm trying to set up a WSS(Secured Web Socket) using Nettosphere, is there any tutorial or reference, working sample available?
I was unable to find one...

**Comment by jdo1** [comment]
@rahulva : This worked for me:
- install strong encryption package (http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) - without modern browsers will fail during SSL handshake

- use in the Config.Builder the call **sslContext(..)** with **org.jboss.netty.handler.ssl.SslContext** param, the method with **javax.net.ssl.SSLContext** doesnt work (seems to be ignored inside Netty)

- the **org.jboss.netty.handler.ssl.SslContext** you can create like this:
```
       File cert = new File("path/to/cert.pem");
       File key = new File("path/to/key.pem.pcks8");
       SslContext sslNettyContext = SslContext.newServerContext(SslProvider.JDK, cert, key, "thePassword");

       Config config = new Config.Builder()
                .port(port)
                .host("127.0.0.1")
                .sslContext(sslNettyContext)
                .resource(new Handler() {
                    @Override
                    public void handle(AtmosphereResource r) {
                        r.getResponse().write("Secure Hello World").closeStreamOrWriter();
                    }
                }).build();

       server = new Nettosphere.Builder().config(config).build();
       server.start();
```
- note that the key needs to be PKCS format - I converted from "normal" via:
```
    openssl pkcs8 -topk8 -inform PEM -outform PEM -in key.pem -out key.pem.pcks8
```

**Comment by aguel** [comment]
I've been struggling with implementing Nettosphere with keystore file (JKS). Any example of code snippet please? Thanks
