### ISSUE TITLE
[Firefox] [NettoSphere] ManagedService Disconnect never called

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/nettosphere#80]
See https://github.com/Atmosphere/atmosphere/issues/1830

**Comment by jfarcand** [comment]
@artvel I can't reproduce your issue with Atmosphere 2.3.0 and NettoSphere 2.3.0 (both SNAPSHOT).
```java
15:14:03.390 [New I/O worker #4] DEBUG o.a.i.OnDisconnectInterceptor - AtmosphereResource c01cfb3f-683b-4189-8037-7d67defd8f13 disconnected
15:14:14.575 [New I/O worker #7] DEBUG o.a.i.OnDisconnectInterceptor - AtmosphereResource c009c8f2-19e0-4c65-8a37-d5bcb9c6a34e disconnected
```

**Comment by artvel** [comment]
@jfarcand cool I'll try it, I hope path validation and multiple subscriptions over one connection are easier to manage as well.
