### ISSUE TITLE
Test fails on Windows

### ISSUE THREAD

**Issue by flowersinthesand** [Atmosphere/nettosphere#81]
Discussion from the mailing list: https://groups.google.com/d/msg/atmosphere-framework/TdVlOEVUAqI/yPApc-6guQIJ

Tests are done on Windows 8.1 Pro and Java 7u71.

Here is a set of failed tests:

Test1

    Failed tests: 
      webSocketHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000

Test2

    Failed tests: 
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000
      testProgrammaticDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testProgrammaticDelayBroadcast() didn't finish within the time-out 20000
      testScheduleBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testScheduleBroadcast() didn't finish within the time-out 20000
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000
      testDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayBroadcast() didn't finish within the time-out 20000
      testDelayNextBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayNextBroadcast() didn't finish within the time-out 20000

Test3

    Failed tests: 
      webSocketHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      wssHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000
      testDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayBroadcast() didn't finish within the time-out 20000
      testDelayNextBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayNextBroadcast() didn't finish within the time-out 20000

Test4

    Failed tests: 
      wssHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000
      testProgrammaticDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testProgrammaticDelayBroadcast() didn't finish within the time-out 20000
      testScheduleBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testScheduleBroadcast() didn't finish within the time-out 20000
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000
      testDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayBroadcast() didn't finish within the time-out 20000
      testDelayNextBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayNextBroadcast() didn't finish within the time-out 20000

Test5

    Failed tests: 
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000
      testScheduleBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testScheduleBroadcast() didn't finish within the time-out 20000
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000
      testDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayBroadcast() didn't finish within the time-out 20000
      testDelayNextBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayNextBroadcast() didn't finish within the time-out 20000

The full test log is available from https://gist.github.com/flowersinthesand/50c5ca62d22677415650

**Comment by jfarcand** [comment]
Are you running with JDK 7? This is strange as nothing is displayedin the log.

**Comment by flowersinthesand** [comment]
Yes as you can see `[na:1.7.0_71]` from the exception stack trace. With `java -version`, I got

```
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

By the way 'mvn clean test' for AsyncHttpClient also fails on my environment similarly. https://gist.github.com/flowersinthesand/94dbcd75e4ef77b19a15

**Comment by flowersinthesand** [comment]
I tried the same test on VM. The full test log is available from https://gist.github.com/flowersinthesand/692c6dd2e3c091ea1fea

In this time, Test2 passes the test successfully interestingly and strangely.

mvn --version:

    Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
    Maven home: C:\apache-maven-3.2.5
    Java version: 1.7.0_71, vendor: Oracle Corporation
    Java home: C:\Program Files\Java\jdk1.7.0_71\jre
    Default locale: en_US, platform encoding: Cp1252
    OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

java -version

    java version "1.7.0_71"
    Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
    Java HotSpot(TM) Client VM (build 24.71-b01, mixed mode, sharing)

Test1

    Failed tests: 
      wssHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      webSocketHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000
      testDelayNextBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayNextBroadcast() didn't finish within the time-out 20000

Test3

    Failed tests: 
      webSocketHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testBroadcastFilter(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testBroadcastFilter() didn't finish within the time-out 20000
      testResumeOnBroadcastUsingBroadcasterFactory(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testResumeOnBroadcastUsingBroadcasterFactory() didn't finish within the time-out 20000

Test4

    Failed tests: 
      webSocketHandlerTest(org.atmosphere.nettosphere.test.NettyAtmosphereTest): expected:<Hello World from Nettosphere> but was:<null>
      testDelayBroadcast(org.atmosphere.nettosphere.test.NettyJerseyTest): Method public void org.atmosphere.nettosphere.test.NettyJerseyTest.testDelayBroadcast() didn't finish within the time-out 20000

**Comment by flowersinthesand** [comment]
I don't know it would be helpful but posted a question to AsyncHttpClient to make sure that it's just my case or not. Also I haven't had a problem to pass Netty 3.

https://groups.google.com/d/msg/asynchttpclient/-_8WEB8pGcw/r6oQ6yFaqPIJ

**Comment by flowersinthesand** [comment]
After ignoring webSocketHandlerTest by commenting out Test annotation, I found the test passes. So far it seems that this issue is because of AsyncHttpClient's WebSocket which is discussed through the above link but not sure.

**Comment by flowersinthesand** [comment]
As AsyncHttpClient's WebSocket issue turns out my ISP problem https://groups.google.com/d/msg/asynchttpclient/-_8WEB8pGcw/F8n7I5g5uLEJ, this issue also may be just my case. I'll investigate it more and close the issue if it's right.

**Comment by flowersinthesand** [comment]
I confirmed it's just my case may due to problem from ISP. It turns out that the test passes after disabling network adapter and fails after enabling it again.
